### ISSUE TITLE
twitter posting

### ISSUE THREAD

**Issue by danieljabailey** [danieljabailey/giant_led_cube#4]
tweet peoples times, and maybe even the log of the solution and the initial scramble

**Comment by 46bit** [comment]
frustratingly all of the twitter api libraries for Rust that I've looked at don't compile for WASM

**Comment by 46bit** [comment]
done. solves get posted to https://twitter.com/giant_cube_bot, and new record times get posted with an extra-celebratory message. code is in https://github.com/danieljabailey/giant_led_cube/pull/22
